name: daily_logger
description: MVP scaffold for DailyLogger (Flutter)

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^13.0.0
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.34
  uuid: ^3.0.7
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  drift_dev: ^2.17.0
